destination: ./_site
auto:        false
lsi:         false
server_port: 4000
pygments:    true
markdown:    kramdown
#permalink:   date
permalink:   pretty
baseurl:    "/"
paginate:    5
paginate_path: "page:num"
maruku:
  use_tex:   false
  use_divs:  false
  png_dir:   images/latex/
  png_url:   /images/latex/
exclude:
  - README.txt
  - Rakefile

  

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#        
analytics :
  provider : google
  google : 
      tracking_id : 'UA-56699291-1'
 
